const properties = {
	attachment: {
		id: true,
		filename: true,
		contentType: true,
		url: true,
		proxyUrl: true,
	},
	channel: {
		guildId: true,
		position: true,
		id: true,
		name: true,
		parentId: true,
		type: true,
		rateLimitPerUser: true,
		permissionOverwrites: true,
	},
	forumTag: {},
	emoji: {
		id: true,
		name: true,
		roles: true,
		user: true,
	},
	defaultReactionEmoji: {},
	guild: {
		description: true,
		icon: true,
		id: true,
		name: true,
		roles: true,
		emojis: true,
		members: true,
		channels: true,
		ownerId: true,
		memberCount: true,
		shardId: true,
		voiceStates: true,
	},
	interaction: {
		id: true,
		applicationId: true,
		type: true,
		guildId: true,
		channelId: true,
		member: true,
		user: true,
		token: true,
		data: true,
		locale: true,
		guildLocale: true,
	},
	invite: {},
	member: {
		avatar: true,
		permissions: true,
		user: true,
		nick: true,
		communicationDisabledUntil: true,
		id: true,
		guildId: true,
		roles: true,
		joinedAt: true,
	},
	message: {
		guildId: true,
		components: true,
		id: true,
		type: true,
		channelId: true,
		content: true,
		embeds: true,
		author: true,
		attachments: true,
		interaction: true,
		messageReference: true,
	},
	messageSnapshot: {},
	messageInteractionMetadata: {},
	messageInteraction: {},
	messageReference: {},
	messageCall: {},
	role: {
		guildId: true,
		id: true,
		position: true,
		name: true,
		permissions: true,
		color: true,
	},
	scheduledEvent: {},
	scheduledEventRecurrenceRule: {},
	stageInstance: {},
	inviteStageInstance: {},
	sticker: {},
	user: {
		avatar: true,
		discriminator: true,
		id: true,
		username: true,
		toggles: true,
	},
	avatarDecorationData: {},
	webhook: {},
	guildOnboarding: {},
	guildOnboardingPrompt: {},
	guildOnboardingPromptOption: {},
	entitlement: {},
	sku: {},
	voiceState: {
		guildId: true,
		channelId: true,
		userId: true,
	},
	poll: {},
	pollAnswer: {},
	pollResult: {},
	pollAnswerCount: {},
	pollMedia: {},
} as const satisfies Discord.DesiredProperties;
type Properties = typeof properties;

export default Object.freeze(properties);
export type { Properties };
