const properties = {
	activityInstance: {
		applicationId: false,
		instanceId: false,
		launchId: false,
		location: false,
		users: false,
	},
	activityLocation: {
		id: false,
		kind: false,
		channelId: false,
		guildId: false,
	},
	attachment: {
		id: true,
		filename: true,
		contentType: true,
		url: true,
		proxyUrl: true,
		title: false,
		size: true,
		description: false,
		height: false,
		width: false,
		ephemeral: false,
		duration_secs: false,
		waveform: false,
		flags: false,
	},
	channel: {
		guildId: true,
		position: true,
		id: true,
		name: true,
		parentId: true,
		type: true,
		rateLimitPerUser: true,
		permissionOverwrites: true,
		defaultReactionEmoji: false,
		member: false,
		applicationId: false,
		flags: false,
		topic: false,
		lastMessageId: false,
		bitrate: false,
		userLimit: false,
		ownerId: false,
		lastPinTimestamp: false,
		rtcRegion: false,
		videoQualityMode: false,
		messageCount: false,
		memberCount: false,
		defaultAutoArchiveDuration: false,
		permissions: false,
		recipients: false,
		icon: false,
		totalMessageSent: false,
		availableTags: false,
		appliedTags: false,
		defaultThreadRateLimitPerUser: false,
		defaultSortOrder: false,
		defaultForumLayout: false,
		threadMetadata: false,
	},
	forumTag: {
		id: false,
		emojiId: false,
		emojiName: false,
		name: false,
		moderated: false,
	},
	emoji: {
		id: true,
		name: true,
		roles: true,
		user: true,
	},
	defaultReactionEmoji: {
		emojiId: false,
		emojiName: false,
	},
	guild: {
		description: true,
		icon: true,
		id: true,
		name: true,
		roles: true,
		emojis: true,
		members: true,
		channels: true,
		ownerId: true,
		memberCount: true,
		shardId: true,
		voiceStates: true,
		applicationId: false,
		approximateMemberCount: false,
		approximatePresenceCount: false,
		toggles: false,
		permissions: false,
		owner: false,
		afkTimeout: false,
		widgetEnabled: false,
		verificationLevel: false,
		defaultMessageNotifications: false,
		explicitContentFilter: false,
		mfaLevel: false,
		systemChannelFlags: false,
		large: false,
		unavailable: false,
		maxPresences: false,
		maxMembers: false,
		vanityUrlCode: false,
		premiumTier: false,
		premiumSubscriptionCount: false,
		maxVideoChannelUsers: false,
		maxStageVideoChannelUsers: false,
		nsfwLevel: false,
		premiumProgressBarEnabled: false,
		iconHash: false,
		splash: false,
		discoverySplash: false,
		afkChannelId: false,
		widgetChannelId: false,
		systemChannelId: false,
		rulesChannelId: false,
		joinedAt: false,
		presences: false,
		banner: false,
		preferredLocale: false,
		publicUpdatesChannelId: false,
		welcomeScreen: false,
		stageInstances: false,
		stickers: false,
		safetyAlertsChannelId: false,
	},
	interaction: {
		id: true,
		applicationId: true,
		type: true,
		guildId: true,
		channelId: true,
		member: true,
		user: true,
		token: true,
		data: true,
		locale: true,
		guildLocale: true,
		channel: false,
		guild: false,
		message: false,
		authorizingIntegrationOwners: false,
		version: false,
		appPermissions: false,
		context: false,
	},
	interactionCallback: {
		id: false,
		type: false,
		activityInstanceId: false,
		responseMessageId: false,
		responseMessageLoading: false,
		responseMessageEphemeral: false,
	},
	interactionCallbackResponse: {
		interaction: false,
		resource: false,
	},
	interactionResource: {
		activityInstance: false,
		message: false,
		type: false,
	},
	subscription: {
		id: false,
		userId: false,
		status: false,
		skuIds: false,
		entitlementIds: false,
		currentPeriodStart: false,
		currentPeriodEnd: false,
		canceledAt: false,
		country: false,
		renewalSkuIds: false,
	},
	soundboardSound: {
		user: false,
		guildId: false,
		emojiId: false,
		emojiName: false,
		name: false,
		available: false,
		soundId: false,
		volume: false,
	},
	invite: {
		stageInstance: false,
		channelId: false,
		guildId: false,
		type: false,
		code: false,
		createdAt: false,
		inviter: false,
		maxAge: false,
		maxUses: false,
		targetType: false,
		targetUser: false,
		targetApplication: false,
		temporary: false,
		uses: false,
		approximateMemberCount: false,
		expiresAt: false,
		guildScheduledEvent: false,
		approximatePresenceCount: false,
	},
	member: {
		avatar: true,
		permissions: true,
		user: true,
		nick: true,
		communicationDisabledUntil: true,
		id: true,
		guildId: true,
		roles: true,
		joinedAt: true,
		avatarDecorationData: false,
		toggles: false,
		banner: false,
		premiumSince: false,
	},
	message: {
		guildId: true,
		components: true,
		id: true,
		type: true,
		channelId: true,
		content: true,
		embeds: true,
		author: true,
		attachments: true,
		interaction: true,
		messageReference: true,
		member: false,
		poll: false,
		applicationId: false,
		activity: false,
		application: false,
		editedTimestamp: false,
		interactionMetadata: false,
		mentions: false,
		mentionedChannelIds: false,
		mentionedRoleIds: false,
		referencedMessage: false,
		messageSnapshots: false,
		nonce: false,
		reactions: false,
		stickerItems: false,
		thread: false,
		webhookId: false,
		call: false,
	},
	messageSnapshot: {
		message: false,
	},
	messageInteractionMetadata: {
		user: false,
		id: false,
		type: false,
		targetUser: false,
		authorizingIntegrationOwners: false,
		originalResponseMessageId: false,
		targetMessageId: false,
		interactedMessageId: false,
		triggeringInteractionMetadata: false,
	},
	messageInteraction: {
		member: false,
		user: false,
		id: false,
		type: false,
		name: false,
	},
	messageReference: {
		channelId: false,
		guildId: false,
		messageId: false,
	},
	messageCall: {
		participants: false,
		endedTimestamp: false,
	},
	role: {
		guildId: true,
		id: true,
		position: true,
		name: true,
		permissions: true,
		color: true,
		flags: false,
		tags: false,
		toggles: false,
		icon: false,
		unicodeEmoji: false,
	},
	scheduledEvent: {
		location: false,
		id: false,
		channelId: false,
		guildId: false,
		description: false,
		name: false,
		creatorId: false,
		scheduledStartTime: false,
		scheduledEndTime: false,
		privacyLevel: false,
		status: false,
		entityType: false,
		entityId: false,
		creator: false,
		userCount: false,
		image: false,
		recurrenceRule: false,
	},
	scheduledEventRecurrenceRule: {
		count: false,
		start: false,
		end: false,
		frequency: false,
		interval: false,
		byWeekday: false,
		byNWeekday: false,
		byMonth: false,
		byMonthDay: false,
		byYearDay: false,
	},
	stageInstance: {
		id: false,
		channelId: false,
		guildId: false,
		topic: false,
		guildScheduledEventId: false,
	},
	inviteStageInstance: {
		members: false,
		participantCount: false,
		speakerCount: false,
		topic: false,
	},
	sticker: {
		user: false,
		id: false,
		guildId: false,
		description: false,
		type: false,
		name: false,
		packId: false,
		tags: false,
		formatType: false,
		available: false,
		sortValue: false,
	},
	user: {
		avatar: true,
		discriminator: true,
		id: true,
		username: true,
		toggles: true,
		avatarDecorationData: false,
		flags: false,
		globalName: false,
		locale: false,
		premiumType: false,
		publicFlags: false,
		accentColor: false,
		email: false,
		banner: false,
	},
	avatarDecorationData: {
		asset: false,
		skuId: false,
	},
	webhook: {
		user: false,
		applicationId: false,
		id: false,
		channelId: false,
		guildId: false,
		url: false,
		type: false,
		name: false,
		token: false,
		avatar: false,
		sourceGuild: false,
		sourceChannel: false,
	},
	guildOnboarding: {
		guildId: false,
		prompts: false,
		defaultChannelIds: false,
		enabled: false,
		mode: false,
	},
	guildOnboardingPrompt: {
		id: false,
		title: false,
		type: false,
		options: false,
		singleSelect: false,
		required: false,
		inOnboarding: false,
	},
	guildOnboardingPromptOption: {
		emoji: false,
		id: false,
		title: false,
		description: false,
		channelIds: false,
		roleIds: false,
	},
	entitlement: {
		applicationId: false,
		id: false,
		guildId: false,
		skuId: false,
		userId: false,
		type: false,
		deleted: false,
		startsAt: false,
		endsAt: false,
		consumed: false,
	},
	sku: {
		applicationId: false,
		id: false,
		flags: false,
		type: false,
		name: false,
		slug: false,
	},
	voiceState: {
		sessionId: true,
		guildId: true,
		channelId: true,
		userId: true,
		toggles: true,
		requestToSpeakTimestamp: false,
	},
	poll: {
		question: false,
		answers: false,
		expiry: false,
		allowMultiselect: false,
		layoutType: false,
		results: false,
	},
	pollAnswer: {
		pollMedia: false,
		answerId: false,
	},
	pollResult: {
		isFinalized: false,
		answerCounts: false,
	},
	pollAnswerCount: {
		id: false,
		count: false,
		meVoted: false,
	},
	pollMedia: {
		emoji: false,
		text: false,
	},
} as const satisfies Discord.TransformersDesiredProperties;
type SelectedDesiredProperties = typeof properties;
type DesiredProperties = Discord.CompleteDesiredProperties<Record<string, unknown>, true>;
type DesiredPropertiesBehaviour = Discord.DesiredPropertiesBehavior.RemoveKey;

export default Object.freeze(properties);
export type { SelectedDesiredProperties, DesiredProperties, DesiredPropertiesBehaviour };
