import { PartOfSpeech } from "../lib/commands/language/dictionaries/part-of-speech";
import { LocalisationLanguage } from "./languages";

export default {
	languages: {
		"Armenian/Eastern": "languages.armenian.eastern",
		"Armenian/Western": "languages.armenian.western",
		Dutch: "languages.dutch",
		"English/American": "languages.english.american",
		"English/British": "languages.english.british",
		Finnish: "languages.finnish",
		French: "languages.french",
		German: "languages.german",
		Greek: "languages.greek",
		Hungarian: "languages.hungarian",
		"Norwegian/Bokmål": "languages.norwegian.bokmal",
		Polish: "languages.polish",
		Romanian: "languages.romanian",
		Turkish: "languages.turkish",
	} as const satisfies Record<LocalisationLanguage, string>,
	partsOfSpeech: {
		noun: "words.noun",
		verb: "words.verb",
		adjective: "words.adjective",
		adverb: "words.adverb",
		adposition: "words.adposition",
		article: "words.article",
		"proper-noun": "words.properNoun",
		letter: "words.letter",
		character: "words.character",
		phrase: "words.phrase",
		idiom: "words.idiom",
		symbol: "words.symbol",
		syllable: "words.syllable",
		numeral: "words.numeral",
		initialism: "words.initialism",
		particle: "words.particle",
		punctuation: "words.punctuation",
		affix: "words.affix",
		pronoun: "words.pronoun",
		determiner: "words.determiner",
		conjunction: "words.conjunction",
		interjection: "words.interjection",
		unknown: "words.unknown",
	} as const satisfies Record<PartOfSpeech, string>,
};
