import { PartOfSpeech } from "../lib/commands/language/dictionaries/part-of-speech";
import { LocalisationLanguage } from "./languages";

export default {
	languages: {
		"Armenian/Eastern": "languages.armenian.eastern",
		"Armenian/Western": "languages.armenian.western",
		Dutch: "languages.dutch",
		"English/American": "languages.english.american",
		"English/British": "languages.english.british",
		Finnish: "languages.finnish",
		French: "languages.french",
		German: "languages.german",
		Greek: "languages.greek",
		Hungarian: "languages.hungarian",
		"Norwegian/Bokmål": "languages.norwegian.bokmal",
		Polish: "languages.polish",
		Romanian: "languages.romanian",
		Turkish: "languages.turkish",
	} as const satisfies Record<LocalisationLanguage, string>,
	deeplLanguages: {
		Armenian: "languages.armenian",
		Belarusian: "languages.belarusian",
		Bulgarian: "languages.bulgarian",
		Chinese: "languages.chinese",
		"Chinese (simplified)": "languages.chinese.simplified",
		Czech: "languages.czech",
		Danish: "languages.danish",
		Dutch: "languages.dutch",
		English: "languages.english",
		"English (American)": "languages.english.american",
		"English (British)": "languages.english.british",
		Estonian: "languages.estonian",
		Finnish: "languages.finnish",
		French: "languages.french",
		German: "languages.german",
		Greek: "languages.greek",
		Hungarian: "languages.hungarian",
		Indonesian: "languages.indonesian",
		Italian: "languages.italian",
		Japanese: "languages.japanese",
		Korean: "languages.korean",
		Latvian: "languages.latvian",
		Lithuanian: "languages.lithuanian",
		Norwegian: "languages.norwegian",
		"Norwegian (Bokmål)": "languages.norwegian.bokmal",
		Polish: "languages.polish",
		Portuguese: "languages.portuguese",
		"Portuguese (Brazilian)": "languages.portuguese.brazilian",
		"Portuguese (European)": "languages.portuguese.european",
		Romanian: "languages.romanian",
		Russian: "languages.russian",
		Slovak: "languages.slovak",
		Slovenian: "languages.slovenian",
		Spanish: "languages.spanish",
		Swedish: "languages.swedish",
		Turkish: "languages.turkish",
		Ukrainian: "languages.ukrainian",
	} satisfies Record<string, string> as Record<string, string>,
	partsOfSpeech: {
		noun: "words.noun",
		verb: "words.verb",
		adjective: "words.adjective",
		adverb: "words.adverb",
		adposition: "words.adposition",
		article: "words.article",
		expression: "words.expression",
		"proper-noun": "words.properNoun",
		letter: "words.letter",
		character: "words.character",
		phrase: "words.phrase",
		idiom: "words.idiom",
		symbol: "words.symbol",
		syllable: "words.syllable",
		numeral: "words.numeral",
		initialism: "words.initialism",
		particle: "words.particle",
		punctuation: "words.punctuation",
		affix: "words.affix",
		pronoun: "words.pronoun",
		determiner: "words.determiner",
		conjunction: "words.conjunction",
		interjection: "words.interjection",
		unknown: "words.unknown",
	} as const satisfies Record<PartOfSpeech, string>,
};
