import { inferLanguages } from 'logos/assets/localisations/utils.ts';

// Do not change key names.
const localisationsByLanguage = inferLanguages({
	'Armenian': {
		'English': 'Armenian',
		'Hungarian': 'Örmény',
		'Polish': 'Ormiański',
		'Romanian': 'Armeană',
	},
	'Belarusian': {
		'English': 'Belarusian',
		'Hungarian': 'Fehérorosz',
		'Polish': 'Białoruski',
		'Romanian': 'Belarusă',
	},
	'Bulgarian': {
		'English': 'Bulgarian',
		'Hungarian': 'Bolgár',
		'Polish': 'Bułgarski',
		'Romanian': 'Bulgară',
	},
	'Chinese': {
		'English': 'Chinese',
		'Hungarian': 'Kínai',
		'Polish': 'Chiński',
		'Romanian': 'Chineză',
	},
	'Chinese (simplified)': {
		'English': 'Chinese (Simplified)',
		'Hungarian': 'Kínai (Egyszerűsített)',
		'Polish': 'Chiński (Uproszczony)',
		'Romanian': 'Chineză (Simplificată)',
	},
	'Czech': {
		'English': 'Czech',
		'Hungarian': 'Cseh',
		'Polish': 'Czeski',
		'Romanian': 'Cehă',
	},
	'Danish': {
		'English': 'Danish',
		'Hungarian': 'Dán',
		'Polish': 'Duński',
		'Romanian': 'Daneză',
	},
	'Dutch': {
		'English': 'Dutch',
		'Hungarian': 'Holland',
		'Polish': 'Niderlandzki',
		'Romanian': 'Neerlandeză',
	},
	'English': {
		'English': 'English',
		'Hungarian': 'Angol',
		'Polish': 'Angielski',
		'Romanian': 'Engleză',
	},
	'English (American)': {
		'English': 'English (American)',
		'Hungarian': 'Angol (Amerikai)',
		'Polish': 'Angielski (Amerykański)',
		'Romanian': 'Engleză (Americană)',
	},
	'English (British)': {
		'English': 'English (British)',
		'Hungarian': 'Angol (Brit)',
		'Polish': 'Angielski (Brytyjski)',
		'Romanian': 'Engleză (Britanică)',
	},
	'Estonian': {
		'English': 'Estonian',
		'Hungarian': 'Észt',
		'Polish': 'Estoński',
		'Romanian': 'Estonă',
	},
	'Finnish': {
		'English': 'Finnish',
		'Hungarian': 'Finn',
		'Polish': 'Fiński',
		'Romanian': 'Finlandeză',
	},
	'French': {
		'English': 'French',
		'Hungarian': 'Francia',
		'Polish': 'Francuski',
		'Romanian': 'Franceză',
	},
	'German': {
		'English': 'German',
		'Hungarian': 'Német',
		'Polish': 'Niemiecki',
		'Romanian': 'Germană',
	},
	'Greek': {
		'English': 'Greek',
		'Hungarian': 'Görög',
		'Polish': 'Grecki',
		'Romanian': 'Greacă',
	},
	'Hungarian': {
		'English': 'Hungarian',
		'Hungarian': 'Magyar',
		'Polish': 'Węgierski',
		'Romanian': 'Maghiară',
	},
	'Indonesian': {
		'English': 'Indonesian',
		'Hungarian': 'Indonéz',
		'Polish': 'Indonezyjski',
		'Romanian': 'Indoneziană',
	},
	'Italian': {
		'English': 'Italian',
		'Hungarian': 'Olasz',
		'Polish': 'Włoski',
		'Romanian': 'Italiană',
	},
	'Japanese': {
		'English': 'Japanese',
		'Hungarian': 'Japán',
		'Polish': 'Japoński',
		'Romanian': 'Japoneză',
	},
	'Korean': {
		'English': 'Korean',
		'Hungarian': 'Koreai',
		'Polish': 'Korejski',
		'Romanian': 'Coreeană',
	},
	'Latvian': {
		'English': 'Latvian',
		'Hungarian': 'Lett',
		'Polish': 'Łotewski',
		'Romanian': 'Letonă',
	},
	'Lithuanian': {
		'English': 'Lithuanian',
		'Hungarian': 'Litván',
		'Polish': 'Litewski',
		'Romanian': 'Lituaniană',
	},
	'Norwegian (Bokmål)': {
		'English': 'Norwegian',
		'Hungarian': 'Norvég',
		'Polish': 'Norweski',
		'Romanian': 'Norvegiană',
	},
	'Polish': {
		'English': 'Polish',
		'Hungarian': 'Lengyel',
		'Polish': 'Polski',
		'Romanian': 'Poloneză',
	},
	'Portuguese': {
		'English': 'Portuguese',
		'Hungarian': 'Portugál',
		'Polish': 'Portugalski',
		'Romanian': 'Portugheză',
	},
	'Portuguese (Brazilian)': {
		'English': 'Portuguese (Brazilian)',
		'Hungarian': 'Portugál (Brazíl)',
		'Polish': 'Portugalski (Brazylijski)',
		'Romanian': 'Portugheză (Braziliană)',
	},
	'Portuguese (European)': {
		'English': 'Portuguese (European)',
		'Hungarian': 'Portuguese (Európai)',
		'Polish': 'Portugalski (Europejski)',
		'Romanian': 'Portugheză (Europeană)',
	},
	'Romanian': {
		'English': 'Romanian',
		'Hungarian': 'Román',
		'Polish': 'Rumuński',
		'Romanian': 'Română',
	},
	'Russian': {
		'English': 'Russian',
		'Hungarian': 'Orosz',
		'Polish': 'Rosyjski',
		'Romanian': 'Rusă',
	},
	'Slovak': {
		'English': 'Slovak',
		'Hungarian': 'Szlovák',
		'Polish': 'Słowacki',
		'Romanian': 'Slovacă',
	},
	'Slovenian': {
		'English': 'Slovenian',
		'Hungarian': 'Szlovén',
		'Polish': 'Słoweński',
		'Romanian': 'Slovenă',
	},
	'Spanish': {
		'English': 'Spanish',
		'Hungarian': 'Spanyol',
		'Polish': 'Hiszpański',
		'Romanian': 'Spaniolă',
	},
	'Swedish': {
		'English': 'Swedish',
		'Hungarian': 'Svéd',
		'Polish': 'Szwedzki',
		'Romanian': 'Suedeză',
	},
	'Turkish': {
		'English': 'Turkish',
		'Hungarian': 'Török',
		'Polish': 'Turecki',
		'Romanian': 'Turcă',
	},
	'Ukrainian': {
		'English': 'Ukrainian',
		'Hungarian': 'Ukrán',
		'Polish': 'Ukraiński',
		'Romanian': 'Ucraineană',
	},
});

export { localisationsByLanguage };
