import type { PartOfSpeech } from "logos:constants/parts-of-speech";

export default Object.freeze({
	adjective: "adjective",
	adposition: "adposition",
	adverb: "adverb",
	affix: "affix",
	article: "article",
	"proper noun": "proper-noun",
	letter: "letter",
	character: "character",
	phrase: "phrase",
	idiom: "idiom",
	symbol: "symbol",
	syllable: "syllable",
	numeral: "numeral",
	initialism: "initialism",
	particle: "particle",
	"punctuation mark": "punctuation",
	conjunction: "conjunction",
	determiner: "determiner",
	interjection: "interjection",
	noun: "noun",
	pronoun: "pronoun",
	verb: "verb",
	number: "number",
	ambiposition: "ambiposition",
	circumposition: "circumposition",
	preposition: "preposition",
	postposition: "postposition",
	circumfix: "circumfix",
	classifier: "classifier",
	proverb: "proverb",
	infix: "infix",
	prefix: "prefix",
	root: "root",
	interfix: "interfix",
	suffix: "suffix",
	"combining form": "combining-form",
	"diacritical mark": "diacritical-mark",
	"prepositional phrase": "prepositional-phrase",
	"han character": "han-character",
	hanzi: "hanzi",
	kanji: "kanji",
	hanja: "hanja",
	romanization: "romanization",
	logogram: "logogram",
	determinative: "determinative",
	contraction: "contraction",
	counter: "counter",
	ideophone: "ideophone",
	participle: "participle",
	unknown: "unknown",
} satisfies Record<string, PartOfSpeech>);
