import { PartOfSpeech } from "logos:constants/parts-of-speech";

export default Object.freeze({
	adjective: "adjective",
	adposition: "adposition",
	preposition: "adposition",
	postposition: "adposition",
	adverb: "adverb",
	affix: "affix",
	prefix: "affix",
	suffix: "affix",
	infix: "affix",
	interfix: "affix",
	article: "article",
	"proper noun": "proper-noun",
	letter: "letter",
	character: "character",
	phrase: "phrase",
	idiom: "idiom",
	symbol: "symbol",
	syllable: "syllable",
	numeral: "numeral",
	initialism: "initialism",
	particle: "particle",
	"punctuation mark": "punctuation",
	conjunction: "conjunction",
	determiner: "determiner",
	interjection: "interjection",
	noun: "noun",
	pronoun: "pronoun",
	unknown: "unknown",
	verb: "verb",
} satisfies Record<string, PartOfSpeech>);
