import { PartOfSpeech } from "logos:constants/parts-of-speech";

export default Object.freeze({
	acronyme: "initialism",
	adjectif: "adjective",
	"adjectif court": "adjective",
	"adjectif démonstratif": "adjective",
	"adjectif déterminatif": "determiner",
	"adjectif numéral": "numeral",
	"adjectif long": "adjective",
	"adjectif possessif": "adjective",
	"adjectif qualificatif": "adjective",
	"adjectif verbal": "adjective",
	adposition: "adposition",
	adverbe: "adverb",
	"adverbe de lieu": "adverb",
	"adverbe de manière": "adverb",
	"adverbe de temps": "adverb",
	"adverbe interrogatif": "adverb",
	"adverbe modal": "adverb",
	"adverbe pronominal": "adverb",
	"adverbe relatif": "adverb",
	affixe: "affix",
	antéposition: "adposition",
	article: "article",
	"article défini": "article",
	"article indéfini": "article",
	caractére: "character",
	cardinal: "numeral",
	circonfixe: "affix",
	conjonction: "conjunction",
	"conjonction de coordination": "conjunction",
	"conjonction de subordination": "conjunction",
	démonstratif: "adjective",
	déterminant: "adjective",
	"déterminant démonstratif": "adjective",
	"déterminant possessif": "adjective",
	diacritique: "symbol",
	idiome: "idiom",
	infixe: "affix",
	interfixe: "affix",
	interjection: "interjection",
	"locution adjectivale": "phrase",
	"locution adjective": "phrase",
	"locution adverbiale": "phrase",
	"locution conjonctive": "phrase",
	"locution nominale": "phrase",
	"locution prépositive": "phrase",
	"locution pronominale": "phrase",
	lettre: "letter",
	mot: "unknown",
	"mot composé": "unknown",
	"mot interrogatif": "unknown",
	nom: "noun",
	"nom abstrait": "noun",
	"nom adjectif": "noun",
	"nom collectif": "noun",
	"nom commun": "noun",
	"nom d’agent": "noun",
	"nom d’agente": "noun",
	"nom d'agent": "noun",
	"nom d'agente": "noun",
	"nom de temps": "noun",
	"nom dénombrable": "noun",
	"nom épithète": "noun",
	"nom indénombrable": "noun",
	"nom massif": "noun",
	"nom non comptable": "noun",
	"nom substantif": "noun",
	numéral: "numeral",
	ordinal: "numeral",
	particule: "particle",
	"phrasal verb": "verb",
	phrase: "phrase",
	"phrase complexe": "phrase",
	"phrase simple": "phrase",
	"phrase toute faite": "phrase",
	ponctuation: "punctuation",
	postposition: "adposition",
	préfixe: "affix",
	préposition: "adposition",
	préverbe: "affix",
	pronom: "pronoun",
	"pronom autonome": "pronoun",
	"pronom démonstratif": "pronoun",
	"pronom démonstratif neutre": "pronoun",
	"pronom démonstratif variable": "pronoun",
	"pronom indéfini": "pronoun",
	"pronom interrogatif": "pronoun",
	"pronom personnel": "pronoun",
	"pronom personnel atone": "pronoun",
	"pronom possessif": "pronoun",
	"pronom réfléchi": "pronoun",
	"pronom relatif": "pronoun",
	"pronom tonique": "pronoun",
	"pronom-adjectif": "pronoun",
	proposition: "adposition",
	"proposition dépendante": "adposition",
	"proposition enchâssée relative": "adposition",
	"proposition principale": "adposition",
	"proposition relative": "adposition",
	"proposition subordonnée": "adposition",
	"proposition subordonnée conjonctive": "adposition",
	"proposition subordonnée relative": "adposition",
	sigle: "initialism",
	"signe de ponctuation": "punctuation",
	suffixe: "affix",
	suprafixe: "affix",
	syllabe: "syllable",
	symbole: "symbol",
	verbe: "verb",
	"verbe à affaiblissement": "verb",
	"verbe à deux actants": "verb",
	"verbe à particule": "verb",
	"verbe à trois actants": "verb",
	"verbe à un actant": "verb",
	"verbe actif": "verb",
	"verbe de perception": "verb",
	"verbe de sensation": "verb",
	"verbe d’état": "verb",
	"verbe d'état": "verb",
	"verbe faible": "verb",
	"verbe fort": "verb",
	"verbe hamzé": "verb",
	"verbe impersonnel": "verb",
	"verbe intransitif": "verb",
	"verbe irrégulier": "verb",
	"verbe léger": "verb",
	"verbe mixte": "verb",
	"verbe passif": "verb",
	"verbe principal": "verb",
	"verbe pronominal": "verb",
	"verbe réfléchi": "verb",
	"verbe régulier": "verb",
	"verbe sans actant": "verb",
	"verbe servile": "verb",
	"verbe simple": "verb",
	"verbe support": "verb",
	"verbe transitif": "verb",
} satisfies Record<string, PartOfSpeech>);
