import {
	FeatureLanguage,
	LearningLanguage,
	Locale,
	LocalisationLanguage,
	TranslationLanguage,
} from "./constants/languages";
import { TimeStruct } from "./lib/database/guild";

const PROJECT_NAME = "Logos";
const USER_AGENT = "Logos (https://logos.wordcollector.co.uk)";

const FEATURE_LOCALE: Locale = "eng-US";
const FEATURE_LANGUAGE: FeatureLanguage = "English";
const LEARNING_LOCALE: Locale = "eng-US";
const LEARNING_LANGUAGE: LearningLanguage = "English/American";
const LOCALISATION_LOCALE: Locale = "eng-US";
const LOCALISATION_LANGUAGE: LocalisationLanguage = "English/American";
const TRANSLATION_LANGUAGE: TranslationLanguage = "English/American";

const RESULTS_PER_PAGE = 10;

const RATE_LIMIT = 3;
const RATE_LIMIT_INTERVAL: TimeStruct = [30, "second"];

const MAX_DELETABLE_MESSAGES = 500;
const MAX_INDEXABLE_MESSAGES = 1000;

const REPORT_LIMIT = 2;
const REPORT_INTERVAL: TimeStruct = [30, "minute"];

const RESOURCE_LIMIT = 2;
const RESOURCE_INTERVAL: TimeStruct = [30, "second"];

const SUGGESTION_LIMIT = 3;
const SUGGESTION_INTERVAL: TimeStruct = [2, "hour"];

const TICKET_LIMIT = 2;
const TICKET_INTERVAL: TimeStruct = [1, "day"];

const PRAISE_LIMIT = 3;
const PRAISE_INTERVAL: TimeStruct = [6, "hour"];

const WARN_LIMIT = 3;
const WARN_EXPIRY: TimeStruct = [2, "month"];
const WARN_TIMEOUT: TimeStruct = [1, "day"];

const MUSIC_DISCONNECT_TIMEOUT: TimeStruct = [2, "minute"];
const MAX_VOLUME = 100;
const MAX_HISTORY_ENTRIES = 20;
const MAX_QUEUE_ENTRIES = 20;

const MIN_VOICE_CHANNELS = 0;
const MAX_VOICE_CHANNELS = 5;

const WARN_MESSAGE_DELETE_TIMEOUT = 1000 * 10; // 10 seconds in milliseconds.

const STATUS_CYCLE = 1000 * 10; // 10 seconds in milliseconds.

const SHORT_TEXT_LENGTH = 60;

const ROW_INDENTATION = 2;

const PRIMARY_ADAPTER_QUERY_COUNT = 2;
const SECONDARY_ADAPTER_QUERY_COUNT = 2;
const TERTIARY_ADAPTER_QUERY_COUNT = 3;
const DICTIONARY_PROVISION_THRESHOLD = 0;
const INCLUDE_EXPRESSION_RELATIONS = false;
const DEFINITIONS_PER_VIEW = 5;
const TRANSLATIONS_PER_VIEW = 5;
const EXPRESSIONS_PER_VIEW = 5;
const EXAMPLES_PER_VIEW = 5;
const DEFINITIONS_PER_EXPANDED_VIEW = 1;
const TRANSLATIONS_PER_EXPANDED_VIEW = 1;
const EXPRESSIONS_PER_EXPANDED_VIEW = 1;
const EXAMPLES_PER_EXPANDED_VIEW = 1;
const DICOLINK_REMOVE_SOURCES = ["wiktionnaire"];
const PONS_FUZZY_MATCH = true;

export default {
	PROJECT_NAME,
	USER_AGENT,
	LOCALISATION_LANGUAGE,
	LOCALISATION_LOCALE,
	LEARNING_LANGUAGE,
	LEARNING_LOCALE,
	FEATURE_LANGUAGE,
	FEATURE_LOCALE,
	TRANSLATION_LANGUAGE,
	RESULTS_PER_PAGE,
	RATE_LIMIT,
	RATE_LIMIT_INTERVAL,
	MAX_DELETABLE_MESSAGES,
	MAX_INDEXABLE_MESSAGES,
	REPORT_LIMIT,
	REPORT_INTERVAL,
	RESOURCE_LIMIT,
	RESOURCE_INTERVAL,
	TICKET_LIMIT,
	TICKET_INTERVAL,
	SUGGESTION_LIMIT,
	SUGGESTION_INTERVAL,
	PRAISE_LIMIT,
	PRAISE_INTERVAL,
	WARN_LIMIT,
	WARN_EXPIRY,
	WARN_TIMEOUT,
	MUSIC_DISCONNECT_TIMEOUT,
	MAX_VOLUME,
	MAX_HISTORY_ENTRIES,
	MAX_QUEUE_ENTRIES,
	MIN_VOICE_CHANNELS,
	MAX_VOICE_CHANNELS,
	WARN_MESSAGE_DELETE_TIMEOUT,
	STATUS_CYCLE,
	SHORT_TEXT_LENGTH,
	ROW_INDENTATION,
	PRIMARY_ADAPTER_QUERY_COUNT,
	SECONDARY_ADAPTER_QUERY_COUNT,
	TERTIARY_ADAPTER_QUERY_COUNT,
	DICTIONARY_PROVISION_THRESHOLD,
	INCLUDE_EXPRESSION_RELATIONS,
	DEFINITIONS_PER_VIEW,
	TRANSLATIONS_PER_VIEW,
	EXPRESSIONS_PER_VIEW,
	EXAMPLES_PER_VIEW,
	DEFINITIONS_PER_EXPANDED_VIEW,
	TRANSLATIONS_PER_EXPANDED_VIEW,
	EXPRESSIONS_PER_EXPANDED_VIEW,
	EXAMPLES_PER_EXPANDED_VIEW,
	DICOLINK_REMOVE_SOURCES,
	PONS_FUZZY_MATCH,
};
